<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository
{
    public function findUnpayedByAdmin($admin)
    {
        return $this
            ->createQueryBuilder('b')
            ->innerJoin('b.project', 'p')
            ->innerJoin('p.customer', 'c')
            ->where('c.admin = :admin AND b.amount > b.accountBalance')
            ->orderBy('b.date')
            ->getQuery()
            ->setParameter('admin', $admin)
            ->getResult();
    }

    public function findOfflineByAdmin($admin)
    {
        return $this
            ->createQueryBuilder('b')
            ->innerJoin('b.project', 'p')
            ->innerJoin('p.customer', 'c')
            ->where('c.admin = :admin AND b.shutdownSince IS NOT NULL')
            ->orderBy('b.date')
            ->getQuery()
            ->setParameter('admin', $admin)
            ->getResult();
    }

    public function findByAdmin($admin)
    {
        return $this
            ->createQueryBuilder('b')
            ->innerJoin('b.project', 'p')
            ->innerJoin('p.customer', 'c')
            ->where('c.admin = :admin')
            ->getQuery()
            ->setParameter('admin', $admin)
            ->getResult();
    }

    public function findLaststepByAdmin($laststepDeadline, $admin)
    {
        return $this
            ->createQueryBuilder('b')
            ->innerJoin('b.project', 'p')
            ->innerJoin('p.customer', 'c')
            ->where(
                'b.amount > b.accountBalance
                AND
                c.admin = :admin
                AND
                (
                    b.receivedDuns = 3
                    AND
                    DATE_DIFF(CURRENT_DATE(), b.lastDun) > :laststepDeadline
                )'
            )
            ->getQuery()
            ->setParameter('laststepDeadline', $laststepDeadline)
            ->setParameter('admin', $admin)
            ->getResult();
    }

    public function findLaststep($laststepDeadline)
    {
        return $this
            ->createQueryBuilder('b')
            ->where(
                'b.amount > b.accountBalance
                AND
                (
                    b.receivedDuns = 3
                    AND
                    DATE_DIFF(CURRENT_DATE(), b.lastDun) > :laststepDeadline
                )'
            )
            ->getQuery()
            ->setParameter('laststepDeadline', $laststepDeadline)
            ->getResult();
    }

    public function findDue($firstDunDeadline, $secondDunDeadline, $laststepDeadline)
    {
        return $this
            ->createQueryBuilder('b')
            ->where(
                'b.amount > b.accountBalance
                AND
                b.shutdownSince IS NULL
                AND
                (
                    (
                        COALESCE(b.receivedDuns, 0) = 0
                        AND
                        DATE_DIFF(CURRENT_DATE(), b.date) > b.deadlineDays
                    )
                    OR
                    (
                        b.receivedDuns = 1
                        AND
                        DATE_DIFF(CURRENT_DATE(), b.lastDun) > :firstDunDeadline
                    )
                    OR
                    (
                        b.receivedDuns = 2
                        AND
                        DATE_DIFF(CURRENT_DATE(), b.lastDun) > :secondDunDeadline
                    )
                    OR
                    (
                        b.receivedDuns = 3
                        AND
                        DATE_DIFF(CURRENT_DATE(), b.lastDun) > :laststepDeadline
                    )
                )'
            )
            ->getQuery()
            ->setParameters([
                'firstDunDeadline' => $firstDunDeadline,
                'secondDunDeadline' => $secondDunDeadline,
                'laststepDeadline' => $laststepDeadline
            ])
            ->getResult();
    }
}
