<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Admin;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    function findByAdmin($adminId)
    {
        return $this
            ->createQueryBuilder('p')
            ->innerJoin('p.customer', 'c')
            ->innerJoin('c.admin', 'a')
            ->where('a.id = :id')
            ->getQuery()
            ->setParameter('id', $adminId)
            ->getResult();
    }
}
