imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

assetic:
    node: /usr/bin/node
    filters:
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            mangle: true
            compress: true
            comments: /@preserve|@license|@cc_on|license|LICENSE/
            apply_to: "\.js$"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: problembericht-payment@complex-co.de
            to_email:   bieder.martin@gmail.com
            subject:    Problembericht payment.complex-co.de
            level:      critical
